version: '3.7'

services:
  db:
    image: mysql:8.0.19
    container_name: webflux-mysql
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "13306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Test!@#$$"
      MYSQL_DATABASE: testDB
      MYSQL_USER: testUser
      MYSQL_PASSWORD: testPassword

  redis:
    image: redis:5.0.8
    container_name: webflux-redis
    hostname: redis
    command: redis-server --appendonly yes --requirepass redis12&*
    restart: always
    ports:
      - "16379:6379"